export default{
	state: {
		shopList: [
			{
				id: 1,
				title: "Nike M2K Tekno",
				descr: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore doloremque ex dolores molestias possimus excepturi inventore cupiditate debitis molestiae at ut quis laudantium quae non autem illo, ab quaerat nihil iure veritatis explicabo commodi. Reiciendis accusamus, non omnis architecto assumenda aliquid in mollitia minima ratione provident iusto quos. Sit perferendis rem dolorem assumenda eligendi excepturi facilis voluptatum. Pariatur, ut rerum nisi consequatur modi veniam maxime ratione excepturi, dolor repellat doloribus temporibus corrupti, accusantium iste voluptatibus praesentium deleniti facere reiciendis illo dolores! Dolores debitis provident architecto laboriosam earum placeat odio! Minus iure enim repellendus consequuntur! Iure autem voluptatem veritatis recusandae accusamus pariatur omnis nam, quibusdam unde dolorem nisi expedita sapiente beatae error. Expedita magnam eius debitis consequuntur sunt temporibus, non saepe molestias. Porro, quia. Molestiae commodi placeat nulla unde, doloribus cumque alias qui animi culpa optio voluptate adipisci incidunt minus, ut voluptatibus blanditiis nisi ipsum fugiat corrupti aspernatur molestias debitis. Maiores eum assumenda ex sed soluta recusandae quos dolor deserunt vitae praesentium ipsam, voluptates asperiores quod dolorum dignissimos obcaecati corporis porro reiciendis beatae tempora officiis rem blanditiis. Suscipit porro quod, autem eveniet unde obcaecati nam aut dolores, voluptas placeat minima iusto ducimus doloremque similique labore provident dicta quisquam recusandae sunt. Delectus maiores iste voluptas odio accusantium cumque esse quaerat, sed expedita architecto? Impedit ipsa quasi perspiciatis eaque velit excepturi fugit iste commodi facere blanditiis sint, harum temporibus possimus veniam. Nulla debitis hic velit tenetur voluptates, voluptate error nostrum beatae fugiat sint earum dolores blanditiis laborum adipisci nihil minus, nesciunt repudiandae possimus pariatur optio. Similique recusandae doloremque debitis voluptatibus consequuntur pariatur accusamus, repellat iure quia perspiciatis sit, laboriosam aut quae dolores cum sint consectetur unde minima. Possimus culpa ab odio animi sed? Minus ipsam magni repudiandae, blanditiis libero expedita officia dicta obcaecati? Unde nam cumque dolorem quae tempora voluptates quaerat ab consequuntur!',
				img: require('@/assets/img/m2k.webp')
			},
			{
				id: 2,
				title: "Nike M2K Tekno",
				descr: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore doloremque ex dolores molestias possimus excepturi inventore cupiditate debitis molestiae at ut quis laudantium quae non autem illo, ab quaerat nihil iure veritatis explicabo commodi. Reiciendis accusamus, non omnis architecto assumenda aliquid in mollitia minima ratione provident iusto quos. Sit perferendis rem dolorem assumenda eligendi excepturi facilis voluptatum. Pariatur, ut rerum nisi consequatur modi veniam maxime ratione excepturi, dolor repellat doloribus temporibus corrupti, accusantium iste voluptatibus praesentium deleniti facere reiciendis illo dolores! Dolores debitis provident architecto laboriosam earum placeat odio! Minus iure enim repellendus consequuntur! Iure autem voluptatem veritatis recusandae accusamus pariatur omnis nam, quibusdam unde dolorem nisi expedita sapiente beatae error. Expedita magnam eius debitis consequuntur sunt temporibus, non saepe molestias. Porro, quia. Molestiae commodi placeat nulla unde, doloribus cumque alias qui animi culpa optio voluptate adipisci incidunt minus, ut voluptatibus blanditiis nisi ipsum fugiat corrupti aspernatur molestias debitis. Maiores eum assumenda ex sed soluta recusandae quos dolor deserunt vitae praesentium ipsam, voluptates asperiores quod dolorum dignissimos obcaecati corporis porro reiciendis beatae tempora officiis rem blanditiis. Suscipit porro quod, autem eveniet unde obcaecati nam aut dolores, voluptas placeat minima iusto ducimus doloremque similique labore provident dicta quisquam recusandae sunt. Delectus maiores iste voluptas odio accusantium cumque esse quaerat, sed expedita architecto? Impedit ipsa quasi perspiciatis eaque velit excepturi fugit iste commodi facere blanditiis sint, harum temporibus possimus veniam. Nulla debitis hic velit tenetur voluptates, voluptate error nostrum beatae fugiat sint earum dolores blanditiis laborum adipisci nihil minus, nesciunt repudiandae possimus pariatur optio. Similique recusandae doloremque debitis voluptatibus consequuntur pariatur accusamus, repellat iure quia perspiciatis sit, laboriosam aut quae dolores cum sint consectetur unde minima. Possimus culpa ab odio animi sed? Minus ipsam magni repudiandae, blanditiis libero expedita officia dicta obcaecati? Unde nam cumque dolorem quae tempora voluptates quaerat ab consequuntur!',
				img: require('@/assets/img/m2k.webp')
			},
			{
				id: 3,
				title: "Nike M2K Tekno",
				descr: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore doloremque ex dolores molestias possimus excepturi inventore cupiditate debitis molestiae at ut quis laudantium quae non autem illo, ab quaerat nihil iure veritatis explicabo commodi. Reiciendis accusamus, non omnis architecto assumenda aliquid in mollitia minima ratione provident iusto quos. Sit perferendis rem dolorem assumenda eligendi excepturi facilis voluptatum. Pariatur, ut rerum nisi consequatur modi veniam maxime ratione excepturi, dolor repellat doloribus temporibus corrupti, accusantium iste voluptatibus praesentium deleniti facere reiciendis illo dolores! Dolores debitis provident architecto laboriosam earum placeat odio! Minus iure enim repellendus consequuntur! Iure autem voluptatem veritatis recusandae accusamus pariatur omnis nam, quibusdam unde dolorem nisi expedita sapiente beatae error. Expedita magnam eius debitis consequuntur sunt temporibus, non saepe molestias. Porro, quia. Molestiae commodi placeat nulla unde, doloribus cumque alias qui animi culpa optio voluptate adipisci incidunt minus, ut voluptatibus blanditiis nisi ipsum fugiat corrupti aspernatur molestias debitis. Maiores eum assumenda ex sed soluta recusandae quos dolor deserunt vitae praesentium ipsam, voluptates asperiores quod dolorum dignissimos obcaecati corporis porro reiciendis beatae tempora officiis rem blanditiis. Suscipit porro quod, autem eveniet unde obcaecati nam aut dolores, voluptas placeat minima iusto ducimus doloremque similique labore provident dicta quisquam recusandae sunt. Delectus maiores iste voluptas odio accusantium cumque esse quaerat, sed expedita architecto? Impedit ipsa quasi perspiciatis eaque velit excepturi fugit iste commodi facere blanditiis sint, harum temporibus possimus veniam. Nulla debitis hic velit tenetur voluptates, voluptate error nostrum beatae fugiat sint earum dolores blanditiis laborum adipisci nihil minus, nesciunt repudiandae possimus pariatur optio. Similique recusandae doloremque debitis voluptatibus consequuntur pariatur accusamus, repellat iure quia perspiciatis sit, laboriosam aut quae dolores cum sint consectetur unde minima. Possimus culpa ab odio animi sed? Minus ipsam magni repudiandae, blanditiis libero expedita officia dicta obcaecati? Unde nam cumque dolorem quae tempora voluptates quaerat ab consequuntur!',
				img: require('@/assets/img/m2k.webp')
			},
			{
				id: 4,
				title: "Nike M2K Tekno",
				descr: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore doloremque ex dolores molestias possimus excepturi inventore cupiditate debitis molestiae at ut quis laudantium quae non autem illo, ab quaerat nihil iure veritatis explicabo commodi. Reiciendis accusamus, non omnis architecto assumenda aliquid in mollitia minima ratione provident iusto quos. Sit perferendis rem dolorem assumenda eligendi excepturi facilis voluptatum. Pariatur, ut rerum nisi consequatur modi veniam maxime ratione excepturi, dolor repellat doloribus temporibus corrupti, accusantium iste voluptatibus praesentium deleniti facere reiciendis illo dolores! Dolores debitis provident architecto laboriosam earum placeat odio! Minus iure enim repellendus consequuntur! Iure autem voluptatem veritatis recusandae accusamus pariatur omnis nam, quibusdam unde dolorem nisi expedita sapiente beatae error. Expedita magnam eius debitis consequuntur sunt temporibus, non saepe molestias. Porro, quia. Molestiae commodi placeat nulla unde, doloribus cumque alias qui animi culpa optio voluptate adipisci incidunt minus, ut voluptatibus blanditiis nisi ipsum fugiat corrupti aspernatur molestias debitis. Maiores eum assumenda ex sed soluta recusandae quos dolor deserunt vitae praesentium ipsam, voluptates asperiores quod dolorum dignissimos obcaecati corporis porro reiciendis beatae tempora officiis rem blanditiis. Suscipit porro quod, autem eveniet unde obcaecati nam aut dolores, voluptas placeat minima iusto ducimus doloremque similique labore provident dicta quisquam recusandae sunt. Delectus maiores iste voluptas odio accusantium cumque esse quaerat, sed expedita architecto? Impedit ipsa quasi perspiciatis eaque velit excepturi fugit iste commodi facere blanditiis sint, harum temporibus possimus veniam. Nulla debitis hic velit tenetur voluptates, voluptate error nostrum beatae fugiat sint earum dolores blanditiis laborum adipisci nihil minus, nesciunt repudiandae possimus pariatur optio. Similique recusandae doloremque debitis voluptatibus consequuntur pariatur accusamus, repellat iure quia perspiciatis sit, laboriosam aut quae dolores cum sint consectetur unde minima. Possimus culpa ab odio animi sed? Minus ipsam magni repudiandae, blanditiis libero expedita officia dicta obcaecati? Unde nam cumque dolorem quae tempora voluptates quaerat ab consequuntur!',
				img: require('@/assets/img/m2k.webp')
			},
			{
				id: 5,
				title: "Nike M2K Tekno",
				descr: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore doloremque ex dolores molestias possimus excepturi inventore cupiditate debitis molestiae at ut quis laudantium quae non autem illo, ab quaerat nihil iure veritatis explicabo commodi. Reiciendis accusamus, non omnis architecto assumenda aliquid in mollitia minima ratione provident iusto quos. Sit perferendis rem dolorem assumenda eligendi excepturi facilis voluptatum. Pariatur, ut rerum nisi consequatur modi veniam maxime ratione excepturi, dolor repellat doloribus temporibus corrupti, accusantium iste voluptatibus praesentium deleniti facere reiciendis illo dolores! Dolores debitis provident architecto laboriosam earum placeat odio! Minus iure enim repellendus consequuntur! Iure autem voluptatem veritatis recusandae accusamus pariatur omnis nam, quibusdam unde dolorem nisi expedita sapiente beatae error. Expedita magnam eius debitis consequuntur sunt temporibus, non saepe molestias. Porro, quia. Molestiae commodi placeat nulla unde, doloribus cumque alias qui animi culpa optio voluptate adipisci incidunt minus, ut voluptatibus blanditiis nisi ipsum fugiat corrupti aspernatur molestias debitis. Maiores eum assumenda ex sed soluta recusandae quos dolor deserunt vitae praesentium ipsam, voluptates asperiores quod dolorum dignissimos obcaecati corporis porro reiciendis beatae tempora officiis rem blanditiis. Suscipit porro quod, autem eveniet unde obcaecati nam aut dolores, voluptas placeat minima iusto ducimus doloremque similique labore provident dicta quisquam recusandae sunt. Delectus maiores iste voluptas odio accusantium cumque esse quaerat, sed expedita architecto? Impedit ipsa quasi perspiciatis eaque velit excepturi fugit iste commodi facere blanditiis sint, harum temporibus possimus veniam. Nulla debitis hic velit tenetur voluptates, voluptate error nostrum beatae fugiat sint earum dolores blanditiis laborum adipisci nihil minus, nesciunt repudiandae possimus pariatur optio. Similique recusandae doloremque debitis voluptatibus consequuntur pariatur accusamus, repellat iure quia perspiciatis sit, laboriosam aut quae dolores cum sint consectetur unde minima. Possimus culpa ab odio animi sed? Minus ipsam magni repudiandae, blanditiis libero expedita officia dicta obcaecati? Unde nam cumque dolorem quae tempora voluptates quaerat ab consequuntur!',
				img: require('@/assets/img/m2k.webp')
			},
			{
				id: 6,
				title: "Nike M2K Tekno",
				descr: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore doloremque ex dolores molestias possimus excepturi inventore cupiditate debitis molestiae at ut quis laudantium quae non autem illo, ab quaerat nihil iure veritatis explicabo commodi. Reiciendis accusamus, non omnis architecto assumenda aliquid in mollitia minima ratione provident iusto quos. Sit perferendis rem dolorem assumenda eligendi excepturi facilis voluptatum. Pariatur, ut rerum nisi consequatur modi veniam maxime ratione excepturi, dolor repellat doloribus temporibus corrupti, accusantium iste voluptatibus praesentium deleniti facere reiciendis illo dolores! Dolores debitis provident architecto laboriosam earum placeat odio! Minus iure enim repellendus consequuntur! Iure autem voluptatem veritatis recusandae accusamus pariatur omnis nam, quibusdam unde dolorem nisi expedita sapiente beatae error. Expedita magnam eius debitis consequuntur sunt temporibus, non saepe molestias. Porro, quia. Molestiae commodi placeat nulla unde, doloribus cumque alias qui animi culpa optio voluptate adipisci incidunt minus, ut voluptatibus blanditiis nisi ipsum fugiat corrupti aspernatur molestias debitis. Maiores eum assumenda ex sed soluta recusandae quos dolor deserunt vitae praesentium ipsam, voluptates asperiores quod dolorum dignissimos obcaecati corporis porro reiciendis beatae tempora officiis rem blanditiis. Suscipit porro quod, autem eveniet unde obcaecati nam aut dolores, voluptas placeat minima iusto ducimus doloremque similique labore provident dicta quisquam recusandae sunt. Delectus maiores iste voluptas odio accusantium cumque esse quaerat, sed expedita architecto? Impedit ipsa quasi perspiciatis eaque velit excepturi fugit iste commodi facere blanditiis sint, harum temporibus possimus veniam. Nulla debitis hic velit tenetur voluptates, voluptate error nostrum beatae fugiat sint earum dolores blanditiis laborum adipisci nihil minus, nesciunt repudiandae possimus pariatur optio. Similique recusandae doloremque debitis voluptatibus consequuntur pariatur accusamus, repellat iure quia perspiciatis sit, laboriosam aut quae dolores cum sint consectetur unde minima. Possimus culpa ab odio animi sed? Minus ipsam magni repudiandae, blanditiis libero expedita officia dicta obcaecati? Unde nam cumque dolorem quae tempora voluptates quaerat ab consequuntur!',
				img: require('@/assets/img/m2k.webp')
			},
		]
	},
	mutations:{

	},
	actions: {

	},
	getters: {
		getShopList(state){
			return state.shopList
		},
		getProduct: (state) => (id)=>{
			return state.shopList.find(
				el => el.id == id
			);
		}
			
		
	}
}